services:
    web:
        build: .
        container_name: go_container
        ports:
            - 3001:3001
        environment:
            PORT: 3001
            FRONTEND_HOST: https://statuesque-queijadas-fa6f75.netlify.app
